title: Juan Antonio Soto López
description: > # this means to ignore newlines until "baseurl:"
  Cajón de sastre donde publico información relacionada con la informática que considero interesante compartir
permalink: ':title/'
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Juan Antonio Soto López # add your name
author-img: david-freeman.jpg # add your photo
about-author: Apasionado de la informática, actualmente trabajando como desarrollador full-stack. # add description

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
